const teamList = [
  't.team_id',
  'ts.name',
  't.wikipedia_logo_url as logo_url',
  'ts.wins',
  'ts.losses',
  'cast(ts.wins as float) / cast(ts.games as float) as winning_percentage',
  'ts.points',
  'cast(ts.points as float) / cast(ts.games as float) as points_per_game',
  'ts.opponent_stat_points',
  'cast(ts.opponent_stat_points as float) / cast(ts.games as float) as opponent_points_per_game',
  '(cast(ts.points as float) / cast(ts.games as float)) - (cast(ts.opponent_stat_points as float) / cast(ts.games as float)) as points_per_game_difference',
];

const teamInfo = [
  't.team_id',
  'ts.name',
  't.wikipedia_logo_url as logo_url',
  't.city',
  't.conference',
  't.division',
];

const statsDescriptions = {
  team_id: 'The unique ID of the team',
  name: 'Team name',
  wins: 'Total number of wins',
  losses: 'Total number of losses',
  possessions: "Team's estimated number of possessions",
  games: 'Total games played',
  fantasy_points: 'Total fantasy points',
  minutes: 'Total number of minutes played',
  field_goals_made: 'Total number of field goals made',
  field_goals_attempted: 'Total number of field goals attempted',
  field_goals_percentage: 'Total field goal percentage',
  effective_field_goals_percentage: 'Total effective field goals percentage',
  two_pointers_made: 'Total two pointers made',
  two_pointers_attempted: 'Total two pointers attempted',
  two_pointers_percentage: 'Total two pointers percentage',
  three_pointers_made: 'Total three pointers made',
  three_pointers_attempted: 'Total three pointers attempted',
  three_pointers_percentage: 'Total three pointers percentage',
  free_throws_made: 'Total free throws made',
  free_throws_attempted: 'Total free throws attempted',
  free_throws_percentage: 'Total free throws percentage',
  offensive_rebounds: 'Total offensive rebounds',
  defensive_rebounds: 'Total defensive rebounds',
  rebounds: 'Total rebounds',
  assists: 'Total assists',
  steals: 'Total steals',
  blocked_shots: 'Total blocked shots',
  turnovers: 'Total turnovers',
  personal_fouls: 'Total personal fouls',
  points: 'Total points scored',
  true_shooting_attempts: "The player's true shooting attempts",
  true_shooting_percentage: "The player's true shooting percentage",
  fantasy_points_fan_duel: 'Total FanDuel daily fantasy points scored',
  fantasy_points_draft_kings: 'Total DraftKings daily fantasy points scored',
  fantasy_points_yahoo: 'Total Yahoo daily fantasy points scored',
  fantasy_points_fantasy_draft: 'Total FantasyDraft daily fantasy points scored',
  plus_minus: 'Total plus minus',
  double_doubles: 'Total double-doubles scored',
  triple_doubles: 'Total triple-doubles scored',
};

module.exports = {
  teamList,
  teamInfo,
  statsDescriptions,
};
