version: '3'
services:
  server:
    env_file: .env
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - 3001
    ports:
      - 3001:3001
    container_name: server
    restart: on-failure
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - server
    stdin_open: true
    restart: on-failure
    container_name: client
    links:
      - server
